# Generated by Django 4.2.9 on 2024-03-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_body_homepage_firstscreenbody_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
    ]
