# Generated by Django 4.2.9 on 2024-03-17 11:20

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('home', '0005_alter_homepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_courses',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='courses.coursespage'),
        ),
    ]
