# Generated by Django 4.2.9 on 2024-03-18 08:09

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('home', '0006_homepage_home_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_reviews',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='reviews.reviewspage'),
        ),
    ]
