# Generated by Django 4.2.9 on 2024-03-19 09:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespage',
            name='course_icon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_icon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_icon3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_text1',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_text2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='course_text3',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
