# Generated by Django 4.2.9 on 2024-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursespage_course_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespage',
            name='course_icon1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='course_icon2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='course_icon3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
