# Generated by Django 4.2.9 on 2024-03-25 12:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('courses', '0007_coursespage_course_mailh3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('form_headerh3', models.CharField(blank=True, max_length=255, null=True)),
                ('form_landing_h3', models.CharField(blank=True, max_length=255, null=True)),
                ('form_intro', wagtail.fields.RichTextField(blank=True)),
                ('form_thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='course_mailh3',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='course_mailtext',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='course_thank_you_text',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='to_address',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='courses.formpage'),
        ),
    ]
