# Generated by Django 4.2.9 on 2024-03-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('courses', '0010_alter_myappsettings_contact_block_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='form_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
