# Generated by Django 4.2.9 on 2024-03-27 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('courses', '0011_formpage_form_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappsettings',
            name='modal_form_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Modal Form'),
        ),
    ]
