# Generated by Django 4.2.9 on 2024-04-02 12:36

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_masterclasspage_alter_coursespage_course_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='courses.masterclasspage'),
        ),
    ]
