# Generated by Django 4.2.9 on 2024-04-03 08:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_masterclasspage_mc_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespage',
            name='course_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('color', wagtail.blocks.IntegerBlock(help_text='0 - no, 1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(help_text='0 - no, 1 - external, 2 - internal')), ('left', wagtail.blocks.CharBlock(required=False)), ('right', wagtail.blocks.RichTextBlock(required=False)), ('rightcolor', wagtail.blocks.IntegerBlock(help_text='0 - no, 1 - blue, 2 - red')), ('rightborder', wagtail.blocks.RichTextBlock(required=False)), ('rightfinish', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False))])), ('checklist2', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('inchecklist', wagtail.blocks.StructBlock([('listheader', wagtail.blocks.RichTextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])))]))])))]))], blank=True, use_json_field=True),
        ),
    ]
