# Generated by Django 4.2.9 on 2024-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_masterclasspage_mc_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclasspage',
            name='mc_show_fishki',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='masterclasspage',
            name='mc_show_review',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='masterclasspage',
            name='mc_show_why',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
