# Generated by Django 4.2.9 on 2024-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_reviewslistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewspage',
            name='review_order',
            field=models.IntegerField(default=1),
        ),
    ]
