# Generated by Django 4.2.9 on 2024-03-28 10:59

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория контента',
                'verbose_name_plural': 'Категории контента',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.categories'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_level',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.levels'),
        ),
    ]
