# Generated by Django 4.2.9 on 2024-04-02 09:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_blogpage_blog_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('color', wagtail.blocks.IntegerBlock(help_text='1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(help_text='0 - no, 1 - external, 2 - internal')), ('left', wagtail.blocks.CharBlock(required=False)), ('right', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False))])), ('checklist', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.TextBlock(max_length=250, required=False)), ('text', wagtail.blocks.TextBlock(max_length=250, required=False))])))]))], blank=True, use_json_field=True),
        ),
    ]
